// app/layout.tsx
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { AuthProvider } from '@/app/context/AuthContext';
import { CacheProvider } from '@/lib/CacheContext'; // 🟡 CacheProvider-ийг импортлоно
import Header from '@/components/Header';
import ScrollToTopButton from '@/components/ScrollToTopButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'physX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <CacheProvider>
            <Header />
            <main className="pt-[90px]">{children}</main>
            <Toaster position="top-right" richColors closeButton />
            <ScrollToTopButton />
          </CacheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}